# Конфигурация контейнеров

version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    depends_on:
      - sphinx
    restart: unless-stopped

  sphinx:
    image: sphinxdoc/sphinx
    volumes:
      - ./.:/docs

  site_documentation:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./build/html:/usr/share/nginx/html
