version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/apt/lists:/var/lib/apt/lists
    restart: unless-stopped
    entrypoint: /bin/bash -c "apt-get update && apt-get install -y python3-pip make && pip3 install --upgrade pip && /usr/local/bin/jenkins.sh"

  site_documentation:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - jenkins_home:/jenkins_data
      - ./build/html:/usr/share/nginx/html

volumes:
  jenkins_home:
