version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/apt/lists:/var/lib/apt/lists
    restart: unless-stopped
    command: bash -c "apt-get update && apt-get install -y python3-pip && pip3 install -U sphinx"

  sphinx:
    image: sphinxdoc/sphinx:4.1.2
    volumes:
      - .:/docs

  site_documentation:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./build/html:/usr/share/nginx/html
