version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    depends_on:
      - sphinx

  sphinx:
    image: sphinxdoc/sphinx
    volumes:
      - ./Users/magic/PycharmProjects/mydocs:/docs
    restart: always
