version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
    user: root
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/apt/lists:/var/lib/apt/lists
      - ./requirements.txt:/var/jenkins_home/requirements.txt
    restart: unless-stopped
    entrypoint: /bin/bash -c "apt-get update && apt-get install -y python3-pip make && pip3 install -r /var/jenkins_home/requirements.txt && /usr/local/bin/jenkins.sh"

  sphinx:
    image: sphinxdoc/sphinx:3.5.4
    volumes:
      - .:/docs

  site_documentation:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./build/html:/usr/share/nginx/html
